### ISSUE TITLE
Markbot

### ISSUE THREAD

**Issue by sackxay** [sackxay/frozen-not-in-time#1]
Markbot is not fetching the 960px — after screenshot (for the last hour) Otherwise all is green.
<br>
<img width="800" alt="Screen Shot 2019-10-15 at 5 45 12 AM" src="https://user-images.githubusercontent.com/43139030/66820623-08a3a100-ef0f-11e9-89c8-6a236a74a733.png">

@charlie-quinn

**Comment by charlie-quinn** [comment]
Hey @sackxay I generally direct any strange 🤖markbot issues towards @thomasjbradley, but let's take a look in class together this week to see if we can resolve this one! 🕵️‍♀️

**Comment by thomasjbradley** [comment]
@charlie-quinn Let me know the outcome.

**Comment by charlie-quinn** [comment]
👋 @thomasjbradley this wasn't resolved in class. Let me know if there's anything you can do on your end.

**Comment by thomasjbradley** [comment]
I actually can’t seem to figure it out. It’s especially weird that that it grabs the `1440px` image and not the smaller one.

@charlie-quinn Just go ahead and enter the grade manually. Write a comment about Markbot being broken.

**Comment by sackxay** [comment]
I narrowed the problem down to the seconds value in my cherry animation. I have attached screenshots with the seconds animation value changed and the different Markbot outcomes for each.

<img width="799" alt="Screen Shot 2019-10-17 at 3 37 32 PM" src="https://user-images.githubusercontent.com/43139030/67041683-2da53900-f0f4-11e9-92e9-a3df23367644.png">
<img width="837" alt="Screen Shot 2019-10-17 at 3 38 21 PM" src="https://user-images.githubusercontent.com/43139030/67041684-2da53900-f0f4-11e9-93fc-cad186e8d89b.png">
<img width="793" alt="Screen Shot 2019-10-17 at 3 36 55 PM" src="https://user-images.githubusercontent.com/43139030/67041682-2da53900-f0f4-11e9-9bdb-a2b902973def.png">


@thomasjbradley 
@charlie-quinn

**Comment by thomasjbradley** [comment]
@sackxay That’s interesting. I’ll have to explore some more.
